<?php

namespace App\Tests\Integration\Repository;

use App\Entity\EmailAddress;
use App\Repository\EmailAddressRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\HttpKernel\KernelInterface;

class EmailAddressRepositoryTest extends KernelTestCase
{

    protected function tearDown(): void
    {
        $kernel = self::bootKernel();
        $entityManager = $kernel->getContainer()->get('doctrine')->getManager();
        $entityManager->createQuery('DELETE FROM App\Entity\EmailAddress as e')->execute();

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testFindActiveEmailAddresses(): void
    {

        $kernel = self::bootKernel();
        $entityManager = $kernel->getContainer()->get('doctrine')->getManager();

        /** @var EmailAddressRepository $emailAddressRepository */
        $emailAddressRepository = $entityManager->getRepository(EmailAddress::class);

        $emailAddresses = $emailAddressRepository->findActiveEmailAddresses();
        $this->assertCount(0, $emailAddresses);
    }
}
