<?php

namespace App\Tests\Integration\Repository;

use App\Newsletter\Infrastructure\DoctrineEmailAddressEntity;
use App\Newsletter\Infrastructure\DoctrineEmailAddressRepository;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class EmailAddressRepositoryTest extends KernelTestCase
{

    protected function tearDown(): void
    {
        $kernel = self::bootKernel();
        $entityManager = $kernel->getContainer()->get('doctrine')->getManager();
        $entityManager->createQuery('DELETE FROM App\Newsletter\Infrastructure\DoctrineEmailAddressEntity as e')->execute();

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testFindActiveEmailAddresses(): void
    {

        $kernel = self::bootKernel();
        $entityManager = $kernel->getContainer()->get('doctrine')->getManager();

        /** @var DoctrineEmailAddressRepository $emailAddressRepository */
        $emailAddressRepository = $entityManager->getRepository(DoctrineEmailAddressEntity::class);

        $emailAddresses = $emailAddressRepository->findActiveEmailAddresses();
        $this->assertCount(0, $emailAddresses);
    }
}
