framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command.bus

        buses:
            command.bus:
            query.bus: ~

        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%'
             sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
#            'App\Command\SendWelcomeEmail': async
#            'App\Command\SendEmail': async
            'App\Newsletter\Command\SignIntoNewsletterCommand': sync
#            'App\Query\ListSentEmails': sync
#            'App\Que      ry\ListNewsletterSignups': sync

when@test:
  framework:
      messenger:
          transports:
              # replace with your transport name here (e.g., my_transport: 'in-memory://')
              # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
              async: 'in-memory://'
