name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  REDIS_HOST: 127.0.0.1
  REDIS_PORT: 6379

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.2-alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: '!ChangeMe!'
          POSTGRES_USER: app
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xdebug, pdo_pgsql, pdo
          tools: composer
      - name: Install dependencies
        run: composer install --dev
      - name: Check env
        run: cat .env.test
      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --env=test --no-interaction
        env:
          MESSENGER_TRANSPORT_DSN: 'redis://${{ env.REDIS_HOST}}:${{ env.REDIS_PORT}}/messages'
          DATABASE_URL: "postgresql://app:!ChangeMe!@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/app?serverVersion=15&charset=utf8"
      - name: Run tests
        run: ./vendor/bin/phpunit --coverage-clover clover.xml
        env:
          XDEBUG_MODE: coverage
          MESSENGER_TRANSPORT_DSN: 'redis://${{ env.REDIS_HOST}}:${{ env.REDIS_PORT}}/messages'
          DATABASE_URL: "postgresql://app:!ChangeMe!@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/app?serverVersion=15&charset=utf8"
      - name: Generate test coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          coverage_badge_path: 'badge-coverage.svg'
          push_badge: true
          repo_token: ${{ secrets.REPO_TOKEN }}

